//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17379
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cai.reports {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmrealtimedemo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmrealtimedemo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cai.reports.frmrealtimedemo", typeof(frmrealtimedemo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static bool alarmThresholdLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("alarmThresholdLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Point chartUpdateTimer_Location {
            get {
                object obj = ResourceManager.GetObject("chartUpdateTimer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Point dataRateTimer_Location {
            get {
                object obj = ResourceManager.GetObject("dataRateTimer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap freezePB_Image {
            get {
                object obj = ResourceManager.GetObject("freezePB.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static bool freezePB_Locked {
            get {
                object obj = ResourceManager.GetObject("freezePB.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Size leftPanel_GridSize {
            get {
                object obj = ResourceManager.GetObject("leftPanel.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        internal static bool leftPanel_Locked {
            get {
                object obj = ResourceManager.GetObject("leftPanel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static System.Drawing.Point rightClickContextMenu_Location {
            get {
                object obj = ResourceManager.GetObject("rightClickContextMenu.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap runPB_Image {
            get {
                object obj = ResourceManager.GetObject("runPB.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static bool runPB_Locked {
            get {
                object obj = ResourceManager.GetObject("runPB.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool separator_Locked {
            get {
                object obj = ResourceManager.GetObject("separator.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool simulatedMachineLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("simulatedMachineLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool topLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("topLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool updatePeriodLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("updatePeriodLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool valueA_Locked {
            get {
                object obj = ResourceManager.GetObject("valueA.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool valueALabel_Locked {
            get {
                object obj = ResourceManager.GetObject("valueALabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool valueB_Locked {
            get {
                object obj = ResourceManager.GetObject("valueB.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool valueBLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("valueBLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool valueC_Locked {
            get {
                object obj = ResourceManager.GetObject("valueC.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        internal static bool valueCLabel_Locked {
            get {
                object obj = ResourceManager.GetObject("valueCLabel.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
